server:
  port: 8899
  tomcat:
    accesslog:
      enabled: true
spring:

  security:
    user:
      password: 123456

  freemarker:
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.254.176.75:3306/admin?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456abc
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

